android:
  components:
    # Update Android SDK Tools
    - tools
    - tools

    - build-tools-27.0.2
    - android-27

    # Support library
    - extra-android-support
    - extra-android-m2repository
  script:
    - chmod +x ./gradlew
