language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools
    - android
    - extra-android-m2repository

script: ./gradlew connectedAndroidTest
