language: android
jdk: oraclejdk8
sudo: false

before_install:
- yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - platform-tools
    - tools
    
    - build-tools
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew connectedAndroidTest
